[workspace]
channels = ["conda-forge"]
name = "assignment-4"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[activation.env]
PYTHONPATH = "$PIXI_PROJECT_ROOT"

[tasks]
test = "pytest"

[dependencies]
xarray = "2026.7.*"
pooch = ">=1.9.0,<2"
netcdf4 = ">=1.7.4,<2"
matplotlib = ">=3.11.2,<4"
jupyterlab = ">=4.6.3,<5"
scipy = ">=1.15,<2"
pytest = ">=8,<9"
